### ISSUE TITLE
Crashes with Design Support Library v25.0.0

### ISSUE THREAD

**Issue by PattaFeuFeu** [opacapp/multiline-collapsingtoolbar#25]
After updating to the newest support libraries, an app I use Multiline-Collapsingtoolbar in, crashes.
Attached, you can find a stack trace. I replaced all “personal“ package names by “foo bar baz” but otherwise left everything as-is.

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{foo.bar.baz/foo.bar.baz.DetailActivity}: android.view.InflateException: Binary XML file line #16: Error inflating class net.opacapp.multilinecollapsingtoolbar.CollapsingToolbarLayout
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2702)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5951)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)`

`Caused by android.view.InflateException: Binary XML file line #16: Error inflating class net.opacapp.multilinecollapsingtoolbar.CollapsingToolbarLayout
       at android.view.LayoutInflater.createView(LayoutInflater.java:640)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:933)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(SourceFile:284)
       at android.support.v7.app.AppCompatActivity.setContentView(SourceFile:143)
       at foo.bar.baz.base.ToolbarActivity.onCreate(SourceFile:95)
       at foo.bar.baz.base.DetailActivity.onCreate(SourceFile:52)
       at foo.bar.baz.DetailActivity.onCreate(SourceFile:61)
       at android.app.Activity.performCreate(Activity.java:6289)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2655)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5951)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)`

`Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:614)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:933)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(SourceFile:284)
       at android.support.v7.app.AppCompatActivity.setContentView(SourceFile:143)
       at foo.bar.baz.base.ToolbarActivity.onCreate(SourceFile:95)
       at foo.bar.baz.base.DetailActivity.onCreate(SourceFile:52)
       at foo.bar.baz.DetailActivity.onCreate(SourceFile:61)
       at android.app.Activity.performCreate(Activity.java:6289)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2655)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5951)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)`

`Caused by java.lang.NumberFormatException: Invalid int: "res/color/abc_hint_foreground_material_light.xml"
       at java.lang.Integer.invalidInt(Integer.java:138)
       at java.lang.Integer.parse(Integer.java:410)
       at java.lang.Integer.parseInt(Integer.java:367)
       at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:128)
       at android.content.res.TypedArray.getInt(TypedArray.java:324)
       at net.opacapp.multilinecollapsingtoolbar.CollapsingTextHelper.setExpandedTextAppearance(SourceFile:253)
       at net.opacapp.multilinecollapsingtoolbar.CollapsingToolbarLayout.(SourceFile:185)
       at net.opacapp.multilinecollapsingtoolbar.CollapsingToolbarLayout.(SourceFile:136)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:614)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:933)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(SourceFile:284)
       at android.support.v7.app.AppCompatActivity.setContentView(SourceFile:143)
       at foo.bar.baz.base.ToolbarActivity.onCreate(SourceFile:95)
       at foo.bar.baz.base.DetailActivity.onCreate(SourceFile:52)
       at foo.bar.baz.DetailActivity.onCreate(SourceFile:61)
       at android.app.Activity.performCreate(Activity.java:6289)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2655)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5951)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)`

When setting AppCompat and the Design Support Library to version 24.2.1 instead of 25.0.0, the crash doesn’t occur.

**Comment by johan12345** [comment]
It seems the new version was released just after I updated the library to be based on the Support Library 24.2.1 yesterday 😕. I'll try to do the update to 25.0.0 now.

**Comment by johan12345** [comment]
I have done the update and the bug seems to be fixed. Now I'm just waiting for @raphaelm to push a new release to JCenter :wink:

**Comment by raphaelm** [comment]
1.3.0 is on bintray :)
