### ISSUE TITLE
OutOfMemory issue

### ISSUE THREAD

**Issue by TonyHaddad91** [opacapp/multiline-collapsingtoolbar#32]
Hey, 
I'm facing this issue while I'm using the library on some devices
Any help with this,
Thanks

`Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 3499212 byte allocation with 643850 free bytes and 628KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
       at android.graphics.drawable.VectorDrawable$VectorDrawableState.createCachedBitmapIfNeeded(VectorDrawable.java:711)
       at android.graphics.drawable.VectorDrawable.draw(VectorDrawable.java:278)
       at android.graphics.drawable.TransitionDrawable.draw(TransitionDrawable.java:209)
       at android.widget.ImageView.onDraw(ImageView.java:1169)
       at android.view.View.draw(View.java:16180)
       at android.view.View.updateDisplayListIfDirty(View.java:15103)
       at android.view.View.getDisplayList(View.java:15126)
       at android.view.View.draw(View.java:15901)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
       at android.view.View.draw(View.java:16183)
       at android.support.v4.view.ViewPager.draw(ViewPager.java:2443)
       at android.view.View.updateDisplayListIfDirty(View.java:15103)
       at android.view.View.getDisplayList(View.java:15126)
       at android.view.View.draw(View.java:15901)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
       at android.view.View.draw(View.java:16183)
       at android.widget.FrameLayout.draw(FrameLayout.java:592)
       at android.view.View.updateDisplayListIfDirty(View.java:15103)
       at android.view.View.getDisplayList(View.java:15126)
       at android.view.View.draw(View.java:15901)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
       at android.view.View.updateDisplayListIfDirty(View.java:15098)
       at android.view.View.getDisplayList(View.java:15126)
       at android.view.View.draw(View.java:15901)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
       at net.opacapp.multilinecollapsingtoolbar.CollapsingToolbarLayout.drawChild(CollapsingToolbarLayout.java:342)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
       at android.view.View.draw(View.java:16183)
       at android.widget.FrameLayout.draw(FrameLayout.java:592)
       at net.opacapp.multilinecollapsingtoolbar.CollapsingToolbarLayout.draw(CollapsingToolbarLayout.java:310)
       at android.view.View.updateDisplayListIfDirty(View.java:15103)
       at android.view.View.getDisplayList(View.java:15126)
       at android.view.View.draw(View.java:15901)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
       at android.view.View.updateDisplayListIfDirty(View.java:15098)
       at android.view.View.getDisplayList(View.java:15126)
       at android.view.View.draw(View.java:15901)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1223)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
       at android.view.View.draw(View.java:16183)
       at android.view.View.updateDisplayListIfDirty(View.java:15103)
       at android.view.View.getDisplayList(View.java:15126)
       at android.view.View.draw(View.java:15901)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
       at android.view.View.draw(View.java:16183)
       at android.widget.FrameLayout.draw(FrameLayout.java:592)
       at android.view.View.updateDisplayListIfDirty(View.java:15103)
       at android.view.View.getDisplayList(View.java:15126)
       at android.view.View.draw(View.java:15901)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
       at android.view.View.updateDisplayListIfDirty(View.java:15098)
       at android.view.View.getDisplayList(View.java:15126)
       at android.view.View.draw(View.java:15901)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
       at android.view.View.updateDisplayListIfDirty(View.java:15098)
       at android.view.View.getDisplayList(View.java:15126)
       at android.view.View.draw(View.java:15901)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
       at android.view.View.updateDisplayListIfDirty(View.java:15098)
       at android.view.View.getDisplayList(View.java:15126)
       at android.view.View.draw(View.java:15901)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
       at android.view.View.updateDisplayListIfDirty(View.java:15098)
       at android.view.View.getDisplayList(View.java:15126)
       at android.view.View.draw(View.java:15901)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
       at android.view.View.updateDisplayListIfDirty(View.java:15098)
       at android.view.View.getDisplayList(View.java:15126)
       at android.view.View.draw(View.java:15901)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
       at android.view.View.updateDisplayListIfDirty(View.java:15098)
       at android.view.View.getDisplayList(View.java:15126)
       at android.view.View.draw(View.java:15901)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
       at android.view.View.draw(View.java:16183)
       at android.widget.FrameLayout.draw(FrameLayout.java:592)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2923)
       at android.view.View.updateDisplayListIfDirty(View.java:15103)
       at android.view.View.getDisplayList(View.java:15126)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2751)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2584)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2176)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5938)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)`

**Comment by johan12345** [comment]
It looks like have added an ImageView inside your CollapsingToolbarLayout and are trying to show a large image in it. In this case, the error is not caused by our library. The image is just too large to fit in the device's RAM.
